# Project information
site_name: docs.oneechotech.com
site_description: Site for learning
site_author: "Ketan Patel"
site_url: "https://docs.oneechotech.com"

# Repository
repo_url: https://github.com/ketangit/ketangit.github.io
repo_name: Github
edit_uri: src/master/docs/

# Documentation and theme
theme:
  name: material
  custom_dir: "theme-extension"
  palette:
    primary: "indigo"
    accent: "light blue"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo:
    icon: "cloud"
  language: en
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
      linenums: True
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - Introduction: index.md
